{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "NavigateToDetail"
	},
	"PageToOpen": "/CustomerScanner/Pages/CustomerScanner_CustomerDataSet/CustomerDataSet_Detail.page",
	 "EnablePageHeader": true
}

